version: 2
jobs:
  build:
    working_directory: ~/blog.sugarshin.net
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - restore_cache:
          name: Restoring Cache - dependencies
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: |
            npm run test:coverage && node_modules/.bin/codecov
      - run:
          name: Build Assets
          command: NODE_ENV=production npm run build
      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global user.name 'CircleCI'
              git config --global user.email 's+circleci@sugarshin.net'
              npm run deploy
              curl -XPOST -d '{"text": "Blog has been updated! <https://blog.sugarshin.net>"}' $SLACK_WEBHOOK_URL
            else
              echo 'It was skip deployment because not master branch.'
            fi
