version: 2.1

references:
  workspace_root: &workspace_root
    ~/blog.sugarshin.net
  filter_gh_pages: &filter_gh_pages
    filters:
      branches:
        ignore: gh-pages

orbs:
  slack: circleci/slack@3.4.2
  gh-pages: sugarshin/gh-pages@0.0.6
  npm: sugarshin/npm@0.1.5

executors:
  nodejs:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:12.6.0
        environment:
          TZ: "Asia/Tokyo"
  nodejs_browsers:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:12.6.0-browsers
        environment:
          TZ: "Asia/Tokyo"
  playwright_base:
    working_directory: *workspace_root
    docker:
      - image: sugarshin/playwright-base:2.1.0-node12
        environment:
          TZ: "Asia/Tokyo"

commands:
  build_assets:
    steps:
      - run:
          name: Build Assets
          command: NODE_ENV=production npm run build
      - run:
          name: Prerender
          command: bin/react-snap --cns

jobs:
  test:
    executor: nodejs
    steps:
      - checkout
      - npm/install:
          yarn: true
          cache-key: 'cache-{{ checksum "yarn.lock" }}'
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test:ci
      - store_test_results:
          path: coverage
  build_test:
    executor: nodejs_browsers
    steps:
      - checkout
      - npm/install:
          yarn: true
          cache-key: 'cache-{{ checksum "yarn.lock" }}'
          production: true
      - build_assets
      - store_artifacts:
          path: build
          destination: build
  deploy:
    executor: nodejs_browsers
    steps:
      - checkout
      - npm/install:
          yarn: true
          cache-key: 'cache-{{ checksum "yarn.lock" }}'
          production: true
      - build_assets
      - store_artifacts:
          path: build
          destination: build
      - gh-pages/deploy:
          workspace-root: *workspace_root
          build-dir: build
          git-user: CircleCI
          git-email: s+circleci@sugarshin.net
          ssh-fingerprints: 4f:c7:c2:20:07:b5:11:84:75:b4:e5:94:73:48:9b:4b
  notify_slack:
    machine: true
    steps:
      - slack/notify:
          message: "Blog has been updated! <https://blog.sugarshin.net>"
          mentions: "${SLACK_UUID}"
          webhook: ${SLACK_WEBHOOK_URL}
  e2e_test:
    executor: playwright_base
    steps:
      - checkout
      - npm/install:
          yarn: true
          cache-key: 'cache-{{ checksum "yarn.lock" }}'
      - run:
          command: npm run build:e2e-test
          environment:
            NODE_ENV: production
      - run:
          command: node static-serve
          background: true
          environment:
            PORT: '3000'
            DIR: build-e2e-test
      - run:
          command: npx wait-on@5 http-get://localhost:3000
      - run:
          command: npm run e2e-test:ci
          environment:
            BASE_URL: http://localhost:3000
            ARTIFACTS_DIR: e2e-test-artifacts
      - store_artifacts:
          path: e2e-test-artifacts
          destination: e2e-test-artifacts

workflows:
  test_build_deploy_notify:
    jobs:
      - test:
          <<: *filter_gh_pages
      - build_test:
          <<: *filter_gh_pages
      - e2e_test:
          <<: *filter_gh_pages
      - deploy:
          requires:
            - test
            - build_test
            - e2e_test
          filters:
            branches:
              only: master
      - notify_slack:
          requires:
            - deploy
