version: 2.1

references:
  workspace_root: &workspace_root
    ~/blog.sugarshin.net
  filter_gh_pages: &filter_gh_pages
    filters:
      branches:
        ignore: gh-pages

orbs:
  slack: circleci/slack@1.1.0
  cypress: cypress-io/cypress@1.17.1
  gh-pages: sugarshin/gh-pages@0.0.6
  npm: sugarshin/npm@0.1.5

executors:
  nodejs:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:12.6.0
        environment:
          TZ: "Asia/Tokyo"
  cypress_browsers_chrome:
    docker:
      - image: cypress/browsers:node12.6.0-chrome77
  nodejs_browsers:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:12.6.0-browsers
        environment:
          TZ: "Asia/Tokyo"

jobs:
  test:
    executor: nodejs
    steps:
      - checkout
      - npm/install:
          yarn: true
          cache-key: 'cache-{{ checksum "yarn.lock" }}'
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test:coverage
      - run:
          name: Coverage Report
          command: npm run codecov
  build_test:
    executor: nodejs_browsers
    steps:
      - checkout
      - npm/install:
          yarn: true
          cache-key: 'cache-{{ checksum "yarn.lock" }}'
          production: true
      - run:
          name: Build Assets
          command: NODE_ENV=production npm run build
      - run:
          name: Prerender
          command: bin/react-snap --cns
      - store_artifacts:
          path: build
          destination: build
  deploy:
    executor: nodejs_browsers
    steps:
      - checkout
      - npm/install:
          yarn: true
          cache-key: 'cache-{{ checksum "yarn.lock" }}'
          production: true
      - run:
          name: Build Assets
          command: NODE_ENV=production npm run build
      - run:
          name: Prerender
          command: bin/react-snap --cns
      - store_artifacts:
          path: build
          destination: build
      - gh-pages/deploy:
          workspace-root: *workspace_root
          build-dir: build
          git-user: CircleCI
          git-email: s+circleci@sugarshin.net
          ssh-fingerprints: 4f:c7:c2:20:07:b5:11:84:75:b4:e5:94:73:48:9b:4b
  notify_slack:
    machine: true
    steps:
      - slack/notify:
          message: "Blog has been updated! <https://blog.sugarshin.net>"
          mentions: "${SLACK_UUID}"
          webhook: ${SLACK_WEBHOOK_URL}

workflows:
  test_build_deploy_notify:
    jobs:
      - test:
          <<: *filter_gh_pages
      - build_test:
          <<: *filter_gh_pages
      - cypress/run:
          <<: *filter_gh_pages
          name: e2e_test
          executor: cypress_browsers_chrome
          yarn: true
          cache-key: 'v1-dependencies-cypress-{{ checksum "yarn.lock" }}'
          build: NODE_ENV=production npm run build:e2e-test
          start: PORT=3000 DIR=build-e2e-test node static-serve
          wait-on: 'http-get://localhost:3000'
          browser: chrome
          no-workspace: true
          store_artifacts: true
      - deploy:
          requires:
            - test
            - build_test
            - e2e_test
          filters:
            branches:
              only: master
      - notify_slack:
          requires:
            - deploy
