version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8.9.4
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
      - checkout
      - run:
          name: Configure Git
          command: |
            git config --global user.name 'CircleCI'
            git config --global user.email 's+circleci@sugarshin.net'
      - restore_cache:
          name: Restoring Cache - dependencies
          keys:
            - v1-dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: System information
          command: |
            echo "Node.js $(node -v)"
            echo "npm $(npm -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: |
            npm run test:coverage && node_modules/.bin/codecov
      - save_cache:
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
          key: v1-dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              NODE_ENV=production npm run build
              npm run deploy
              curl -XPOST -d '{"text": "Blog has been updated! <https://blog.sugarshin.net>"}' $SLACK_WEBHOOK_URL
            fi
