version: 2.1

references:
  workspace_root: &workspace_root
    ~/blog.sugarshin.net
  filter_gh_pages: &filter_gh_pages
    filters:
      branches:
        ignore: gh-pages

orbs:
  slack: circleci/slack@1.1.0
  cypress: cypress-io/cypress@1.7.0

executors:
  nodejs:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:10.15.1
        environment:
          TZ: "Asia/Tokyo"
  cypress_browsers_chrome:
    docker:
      - image: cypress/browsers:node10.2.1-chrome74

commands:
  restore_yarn_cache:
    parameters:
      prod:
        type: boolean
        default: false
    steps:
      - restore_cache:
          name: Restoring Yarn Cache
          keys:
            - v2-dependencies-<<# parameters.prod >>prod-<</ parameters.prod >>{{ checksum "yarn.lock" }}
            - v2-dependencies-<<# parameters.prod >>prod-<</ parameters.prod >>
  save_yarn_cache:
    parameters:
      prod:
        type: boolean
        default: false
    steps:
      - save_cache:
          name: Saving Yarn Cache
          key: v2-dependencies-<<# parameters.prod >>prod-<</ parameters.prod >>{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
  configure_git:
    steps:
      - run:
          name: Configure Git
          command: |
            git config --global user.name 'CircleCI'
            git config --global user.email 's+circleci@sugarshin.net'

jobs:
  test:
    executor:
      name: nodejs
    steps:
      - checkout
      - restore_yarn_cache
      - run: yarn install --frozen-lockfile
      - save_yarn_cache
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test:coverage
      - run:
          name: Coverage Report
          command: npm run codecov
  build_test:
    executor:
      name: nodejs
    steps:
      - checkout
      - restore_yarn_cache:
          prod: true
      - run: yarn install --frozen-lockfile --prod
      - save_yarn_cache:
          prod: true
      - run:
          name: Build Assets
          command: NODE_ENV=production npm run build
      - store_artifacts:
          path: build
          destination: build
  deploy:
    executor:
      name: nodejs
    steps:
      - checkout
      - restore_yarn_cache:
          prod: true
      - run: yarn install --frozen-lockfile --prod
      - save_yarn_cache:
          prod: true
      - run:
          name: Build Assets
          command: NODE_ENV=production npm run build
      - store_artifacts:
          path: build
          destination: build
      - configure_git
      - run:
          name: Deploy
          command: /bin/bash scripts/deploy.bash
  notify_slack:
    machine: true
    steps:
      - slack/notify:
          message: "Blog has been updated! <https://blog.sugarshin.net>"
          mentions: "${SLACK_UUID}"
          webhook: ${SLACK_WEBHOOK_URL}

workflows:
  test_build_deploy:
    jobs:
      - test:
          <<: *filter_gh_pages
      - build_test:
          <<: *filter_gh_pages
      - cypress/run:
          <<: *filter_gh_pages
          name: e2e_test
          executor: cypress_browsers_chrome
          yarn: true
          cache-key: 'v1-dependencies-cypress-{{ checksum "yarn.lock" }}'
          build: NODE_ENV=production npm run build:e2e-test
          start: PORT=3000 node e2e-test/server
          wait-on: 'http-get://localhost:3000'
          browser: chrome
          no-workspace: true
          store_artifacts: true
      - deploy:
          requires:
            - test
            - build_test
            - e2e_test
          filters:
            branches:
              only: master
      - notify_slack:
          requires:
            - deploy
