version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8.6.0
    steps:
      - checkout
      - restore_cache:
          name: Restoring Cache - dependencies
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: System information
          command: |
            echo "Node.js $(node -v)"
            echo "npm $(npm -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: |
            npm run test:coverage && node_modules/.bin/codecov
      - save_cache:
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
          key: v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              NODE_ENV=production npm run build
              COMMIT=$(git rev-parse --short HEAD) && node_modules/.bin/gh-pages -d build -xt --repo https://github.com/sugarshin/log.sugarshin.net.git -m "Built artifacts of ${COMMIT} [ci skip]"
              curl -XPOST -d '{"text": "blog has been updated! <https://log.sugarshin.net>"}' $SLACK_WEBHOOK_URL
            fi
