import mirrorKeyValue from 'mirror-key-value'

export default mirrorKeyValue([
  'CLOSE_SIDEBAR',
  'DOCUMENT_HEAD_STATE_CHANGED',
  'FETCH_ARTICLE',
  'LOCATION_CHANGED',
  'OPEN_SIDEBAR',
  'RECEIVE_ARTICLE',
  'RECEIVE_ARTICLE_LIST',
  'RECEIVE_SEARCH_ARTICLE',
  'REQUEST_ARTICLE',
  'REQUEST_ARTICLE_LIST',
  'REQUEST_SEARCH_ARTICLE',
  'SELECT_DATE',
  'SELECT_CATEGORY',
  'TOGGLE_SIDEBAR_DOCKED',
  'TOGGLE_SIDEBAR',
  'USE_CACHED_ARTICLE',
])
