import mirrorKeyValue from 'mirror-key-value';

export default mirrorKeyValue([
  'FETCH_ALL_ARTICLE_LIST',
  'FETCH_ARTICLE',
  'RECEIVE_ARTICLE',
  'RECEIVE_ARTICLES',
  'REQUEST_ARTICLE',
  'REQUEST_ARTICLES',
  'REQUEST_ERROR_ARTICLE',
  'REQUEST_ERROR_ARTICLES',
  'REQUEST_ERROR_SEARCH_ARTICLE',
  'REQUEST_SEARCH_ARTICLE',
  'RECEIVE_SEARCH_ARTICLE',
  'SEARCH_ARTICLE',
  'SELECT_DATE',
  'SELECT_CATEGORY',
  'USE_CACHED_ARTICLE',
  'TOGGLE_SIDEBAR_OPEN',
  'TOGGLE_SIDEBAR_DOCKED'
]);
