module.exports = {
  lang: 'ja',
  domain: 'log.sugarshin.net',
  protocol: 'https:',
  siteName: 'log.sugarshin.net',
  description: 'sugarshin\'s blog',
  copyright: 'sugarshin | Shingo Sato All rights reserved.',
  authorName: 'Shingo Sato',
  authorEmail: 'shinsugar@gmail.com',
  authorURL: 'https://sugarshin.net/',
  authorGitHubUserName: 'sugarshin',
  repositoryName: 'log.sugarshin.net',
  googleSiteVerificationKey: '4O7-qR4PXF2KacXibd4CB6biuOWFLAm_UduYbxa5G4E',
  facebookAppID: '1691251117863979',
  feedURL: 'feed.xml',
  rssURL: 'rss.xml',
}
