name: Deploy

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '.github/workflows/deploy.yml'
      - '.node-version'
      - 'next.config.ts'
      - 'package-lock.json'
      - 'package.json'
      - 'postcss.config.mjs'
      - 'public/**'
      - 'scripts/**'
      - 'src/**'
      - 'tsconfig.json'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
      - '.node-version'
      - 'next.config.ts'
      - 'package-lock.json'
      - 'package.json'
      - 'postcss.config.mjs'
      - 'public/**'
      - 'scripts/**'
      - 'src/**'
      - 'tsconfig.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  DIST_DIR: out
  DIST_PATH: out

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .node-version
      - id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - run: npm ci
      - run: npm run build
        env:
          NEXT_PUBLIC_API_ORIGIN: ${{ vars.API_ORIGIN }}
          NEXT_PUBLIC_APP_ORIGIN: ${{ vars.APP_ORIGIN }}
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          include-hidden-files: true
          name: ${{ env.DIST_DIR }}
          path: ${{ env.DIST_PATH }}
          if-no-files-found: error
  deploy:
    permissions:
      pull-requests: write
    needs: build
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Install npm packages in the deploy job as well to ensure the wrangler CLI version 
      # used in subsequent steps is locked via the lock file
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .node-version
      - id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - run: npm ci

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: ${{ env.DIST_DIR }}
          path: ${{ env.DIST_PATH }}
      - uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy --branch=${{ github.ref_name }} --commit-dirty=true
          wranglerVersion: ${{ env.WRANGLER_VERSION }}
        env:
          WRANGLER_VERSION: 4.28.1
      - uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        if: ${{ success() && github.event_name == 'pull_request' }}
        with:
          message: |
            Preview Deployment Successfully ✅ ${{ steps.deploy.outputs.deployment-url }}
          comment-tag: cloudflare-pages-deployment
